#! /bin/bash
hostnames=(ec2-18-222-189-83.us-east-2.compute.amazonaws.com
    ec2-18-216-216-71.us-east-2.compute.amazonaws.com
    ec2-18-220-185-191.us-east-2.compute.amazonaws.com)

while getopts "p:o:u:n:i:" arg
do
    case $arg in
        p) # Port
            port=$OPTARG
            ;;
        o) # Origin server
            origin=$OPTARG
            ;;
        u) # username
            username=$OPTARG
            ;;
        n) # CDN-specific name
            # echo "name:$OPTARG"
            name=$OPTARG
            ;;
        i) #private key
            keyfile=$OPTARG
            ;;
        ?)
            echo "unknown argument"
        exit 1
        ;;
        esac
done

for host in "${hostnames[@]}"
do
    echo $host
    ssh -i $keyfile -n -f $username@$host "sh -c 'cd ~/scripts/; ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
done

dnsserver=ec2-18-220-138-231.us-east-2.compute.amazonaws.com
echo $dnsserver
ssh -i $keyfile -n -f $username@$dnsserver "sh -c 'cd ~/scripts/; nohup ./dnsserver -p $port -n $name > /dev/null 2>&1 &'"
